FROM ubuntu:18.04

ARG http_proxy
ARG https_proxy

RUN apt update && apt install -qy wget python3 python3-pip libclang1-6.0
RUN pip3 install clang jinja2 pyang

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10

ADD sm/oopt-tai/meta/main.py /usr/lib/python3.6/tai.py
