apiVersion: v1
kind: ConfigMap
metadata:
    name: onl-platform
data:
    platform: "x86-64-kvm-x86-64-r0"

---

apiVersion: v1
kind: Service
metadata:
    name: netopeer2
spec:
    selector:
        app: gs-mgmt
    ports:
    - protocol: TCP
      port: 830

---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: gs-mgmt
    namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: gs-mgmt
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: gs-mgmt
  namespace: default

---

apiVersion: batch/v1
kind: Job
metadata:
    name: prep-gs-mgmt
spec:
    template:
        spec:
            hostPID: true
            restartPolicy: Never
            containers:
            - name: prep-sysrepo
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh","-c", "sysrepoctl -s/var/lib/goldstone/yang/gs --install /var/lib/goldstone/yang/gs/goldstone-tai.yang,/var/lib/goldstone/yang/gs/goldstone-onlp.yang && \
                 sysrepoctl -s /var/lib/goldstone/yang/sonic/common --install /var/lib/goldstone/yang/sonic/common/sonic-common.yang && \
                 sysrepoctl -s /var/lib/goldstone/yang/sonic --install /var/lib/goldstone/yang/sonic/sonic-interface.yang,/var/lib/goldstone/yang/sonic/sonic-port.yang,/var/lib/goldstone/yang/sonic/sonic-portchannel.yang,/var/lib/goldstone/yang/sonic/sonic-vlan.yang "]
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - name: prep-np
              image: docker.io/microsonic/gs-mgmt-netopeer2:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', '$NP2/setup.sh && $NP2/merge_hostkey.sh && $NP2/merge_config.sh']
              env:
              - name: NP2
                value: /usr/local/share/netopeer2/scripts
              - name: NP2_MODULE_OWNER
                value: root
              - name: NP2_MODULE_GROUP
                value: root
              - name: NP2_MODULE_PERMS
                value: "600"
              - name: NP2_MODULE_DIR
                value: /usr/local/share/yang/modules/netopeer2
              volumeMounts:
              - mountPath: /dev/shm
                name: shm
              - mountPath: /var/lib/sysrepo
                name: sysrepo
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-cli
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-cli
    template:
        metadata:
            labels:
                app: gs-mgmt-cli
        spec:
            hostPID: true
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: cli
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'while true; do gscli -c "transponder; show"; sleep 2; done']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              securityContext:
                privileged: true
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-np2
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-np2
    template:
        metadata:
            labels:
                app: gs-mgmt-np2
        spec:
            hostPID: true
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: netopeer2
              image: docker.io/microsonic/gs-mgmt-netopeer2:latest
              imagePullPolicy: IfNotPresent
              command: ['netopeer2-server', '-d', '-v', '2']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-tai
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-tai
    template:
        metadata:
            labels:
                app: gs-mgmt-tai
        spec:
            hostPID: true
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: tai
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'sleep 10 && gssouthd-tai -v']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - name: taish-server
              image: docker.io/microsonic/tai:latest
              imagePullPolicy: IfNotPresent
              command: ['taish_server', '-n', '-v']
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-onlp
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-onlp
    template:
        metadata:
            labels:
                app: gs-mgmt-onlp
        spec:
            hostPID: true
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: onlp
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'ln -sf /lib/platform-config/x86-64-kvm-x86-64-r0/onl/lib/libonlp-x86-64-kvm-x86-64.so /lib/x86_64-linux-gnu/libonlp-platform.so.1 && gssouthd-onlp']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: onl-platform
                mountPath: /etc/onl/
              securityContext:
                capabilities:
                  add:
                  - IPC_OWNER
                  - IPC_LOCK
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: onl-platform
              configMap:
                name: onl-platform

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-sonic
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-sonic
    template:
        metadata:
            labels:
                app: gs-mgmt-sonic
        spec:
            hostPID: true
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: sonic
              image: docker.io/microsonic/gs-mgmt-debug:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'sleep 10 && /usr/bin/gssouthd-sonic -s $SONIC_MGMT_PORT_80_TCP_ADDR -p http']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
