apiVersion: v1
kind: ConfigMap
metadata:
    name: onl-platform
data:
    platform: "x86-64-kvm-x86-64-r0"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: goldstone-version
data:
  versions.json: |
      {"PRODUCT_ID_VERSION": "0.0.8"}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: usonic-config
data:
  lanemap.ini: |
    vEthernet1:1,2,3,4
    vEthernet2:5,6,7,8
  lanemap.ini.j2: "# name lanes\n{% for i in interfaces -%}\n{{ i['name'] }}:{{ i['lanes'] }}\n{% endfor %}"
  port_config.ini: |
    Ethernet1 1,2,3,4
    Ethernet2 5,6,7,8
  port_config.ini.j2: "# name lanes alias index speed\n
{% for i in interfaces -%}\n
{{ '%-15s' | format(i['name']) }} {{ '%-15s' | format(i['lanes']) }} {{ '%-15s' | format(i['alias']) }} {{ '%-5s' | format(i['index']) }} {{ i['speed'] }}\n
{% endfor %}"
  config.bcm: |
    # dummy
  config.bcm.j2: |
    # dummy
  interfaces.json: |
    [
    {"port": 1, "first_lane": 1, "lane_num": 4, "alias_prefix": "QSFP1", "index": 1, "speed": 100000},
    {"port": 2, "first_lane": 5, "lane_num": 4, "alias_prefix": "QSFP2", "index": 5, "speed": 100000}
    ]
  sai.profile: |
    SAI_VS_SWITCH_TYPE=SAI_VS_SWITCH_TYPE_BCM56850
    SAI_VS_INTERFACE_LANE_MAP_FILE=/etc/sonic/lanemap.ini

---

apiVersion: v1
kind: Service
metadata:
    name: netopeer2
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 830
    targetPort: 830
    name: netconf
  selector:
      app: gs-mgmt

---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: gs-mgmt
    namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: gs-mgmt
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: gs-mgmt
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: gs-mgmt-sonic-svc
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: gs-mgmt-sonic-svc
    namespace: default
roleRef:
  kind: ClusterRole
  name: usonic-manage
  apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: gs-mgmt-sonic-svc
   namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: usonic-manage
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","update","patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["*"]

---

apiVersion: batch/v1
kind: Job
metadata:
    name: prep-gs-mgmt
spec:
    template:
        spec:
            restartPolicy: Never
            initContainers: # run prep-sysrepo and prep-np sequentially
            - name: prep-sysrepo
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ["gs-yang.py", "--install", "south-onlp", "south-sonic", "south-tai", "south-system", "xlate-oc"]
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - name: prep-np
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt-netopeer2:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', '$NP2/setup.sh && $NP2/merge_hostkey.sh && $NP2/merge_config.sh']
              env:
              - name: NP2
                value: /usr/local/share/netopeer2/scripts
              - name: NP2_MODULE_OWNER
                value: root
              - name: NP2_MODULE_GROUP
                value: root
              - name: NP2_MODULE_PERMS
                value: "600"
              - name: NP2_MODULE_DIR
                value: /usr/local/share/yang/modules/netopeer2
              volumeMounts:
              - mountPath: /dev/shm
                name: shm
              - mountPath: /var/lib/sysrepo
                name: sysrepo
            containers:
            - name: job-done
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ["sysrepoctl", "-l"]
              volumeMounts:
              - mountPath: /dev/shm
                name: shm
              - mountPath: /var/lib/sysrepo
                name: sysrepo
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-cli
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-cli
    template:
        metadata:
            labels:
                app: gs-mgmt-cli
        spec:
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: cli
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt-north-cli:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'while true; do gscli -c "transponder; show"; sleep 2; done']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-np2
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-np2
    template:
        metadata:
            labels:
                app: gs-mgmt-np2
        spec:
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: netopeer2
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt-netopeer2:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['netopeer2-server', '-d', '-v', '2']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-tai
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-tai
    template:
        metadata:
            labels:
                app: gs-mgmt-tai
        spec:
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            - name: wait-onlp
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', "kubectl wait --for=condition=ready pods/$(kubectl get pods -l app=gs-mgmt-onlp -o jsonpath='{.items[0].metadata.name}')"]
            containers:
            - name: tai
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt-south-tai:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-tai']
              args: ['--taish-server', "127.0.0.1:50051", "--verbose"]
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 1
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 30
                periodSeconds: 10
              ports:
              - name: liveness-port
                containerPort: 8080
            - name: taish-server
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/tai:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['taish_server', '-n', '-v']
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-onlp
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-onlp
    template:
        metadata:
            labels:
                app: gs-mgmt-onlp
        spec:
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: onlp
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt-south-onlp:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'ln -sf /lib/platform-config/x86-64-kvm-x86-64-r0/onl/lib/libonlp-x86-64-kvm-x86-64.so /lib/x86_64-linux-gnu/libonlp-platform.so.1 && gssouthd-onlp -v']
              env:
              - name: PYTHONPATH
                value: /usr/lib/python3/dist-packages
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: onl-platform
                mountPath: /etc/onl/
              securityContext:
                capabilities:
                  add:
                  - IPC_OWNER
                  - IPC_LOCK
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 1
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 30
                periodSeconds: 10
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: onl-platform
              configMap:
                name: onl-platform

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-sonic
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-sonic
    template:
        metadata:
            labels:
                app: gs-mgmt-sonic
        spec:
            serviceAccountName: gs-mgmt-sonic-svc
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: sonic
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt-south-sonic:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-sonic', '-v']
              env:
              - name: USONIC_TEMPLATE_DIR
                value: "/var/lib/usonic"
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: sonic-db-config
                mountPath: /var/run/redis/sonic-db/
              - name: usonic-config
                mountPath: /var/lib/usonic
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 1
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 30
                periodSeconds: 10
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: sonic-db-config
              configMap:
                  name: sonic-db-config
            - name: usonic-config
              configMap:
                  name: usonic-config

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-system
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-system
    template:
        metadata:
            labels:
                app: gs-mgmt-system
        spec:
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: south-system
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt-south-system:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-system', '-v']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: goldstone-version
                mountPath: /etc/goldstone/loader
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: goldstone-version
              configMap:
                  name: goldstone-version
