apiVersion: v1
kind: ServiceAccount
metadata:
    name: north-cli
    labels:
        gs-mgmt: north-cli

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: north-cli
    labels:
        gs-mgmt: north-cli
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: north-cli
  namespace: default

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: north-cli
    labels:
        app: gs-mgmt
        gs-mgmt: north-cli
spec:
    selector:
        matchLabels:
            app: north-cli
    template:
        metadata:
            labels:
                app: north-cli
        spec:
            serviceAccountName: north-cli
            initContainers:
            - name: wait-prep
              image: docker.io/lachlanevenson/k8s-kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: cli
              image: ghcr.io/oopt-goldstone/mgmt/north-cli:latest
              imagePullPolicy: IfNotPresent
              command: ['sleep']
              args: ['infinity']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
