apiVersion: v1
kind: ServiceAccount
metadata:
    name: north-notif
    labels:
        gs-mgmt: north-notif

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: north-notif
    labels:
        gs-mgmt: north-notif
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: north-notif
  namespace: default

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: north-notif
    labels:
        app: gs-mgmt
        gs-mgmt: north-notif
spec:
    selector:
        matchLabels:
            app: north-notif
    template:
        metadata:
            labels:
                app: north-notif
        spec:
            serviceAccountName: north-notif
            initContainers:
            - name: wait-prep
              image: docker.io/lachlanevenson/k8s-kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: notif
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt-north-notif:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['gsnorthd-notif']
              args: ['--verbose']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 1
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 120
                periodSeconds: 1
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
