apiVersion: v1
kind: ConfigMap
metadata:
  name: current
data:
  platform.json: |
    [
      {"interface": {"suffix": "1_1"}, "component": {"name": "port1"}},
      {"interface": {"suffix": "2_1"}, "component": {"name": "port2"}},
      {"interface": {"suffix": "3_1"}, "component": {"name": "port3"}},
      {"interface": {"suffix": "4_1"}, "component": {"name": "port4"}},
      {"interface": {"suffix": "5_1"}, "component": {"name": "port5"}},
      {"interface": {"suffix": "6_1"}, "component": {"name": "port6"}},
      {"interface": {"suffix": "7_1"}, "component": {"name": "port7"}},
      {"interface": {"suffix": "8_1"}, "component": {"name": "port8"}},
      {"interface": {"suffix": "9_1"}, "component": {"name": "port9"}},
      {"interface": {"suffix": "10_1"}, "component": {"name": "port10"}},
      {"interface": {"suffix": "11_1"}, "component": {"name": "port11"}},
      {"interface": {"suffix": "12_1"}, "component": {"name": "port12"}},
      {"interface": {"suffix": "13_1"}, "tai": {"module": {"name": "piu1", "location": "0"}, "hostif": {"name": "0", "index": 0}}},
      {"interface": {"suffix": "14_1"}, "tai": {"module": {"name": "piu1", "location": "0"}, "hostif": {"name": "1", "index": 1}}},
      {"interface": {"suffix": "15_1"}, "tai": {"module": {"name": "piu2", "location": "1"}, "hostif": {"name": "0", "index": 0}}},
      {"interface": {"suffix": "16_1"}, "tai": {"module": {"name": "piu2", "location": "1"}, "hostif": {"name": "1", "index": 1}}},
      {"interface": {"suffix": "17_1"}, "tai": {"module": {"name": "piu3", "location": "2"}, "hostif": {"name": "0", "index": 0}}},
      {"interface": {"suffix": "18_1"}, "tai": {"module": {"name": "piu3", "location": "2"}, "hostif": {"name": "1", "index": 1}}},
      {"interface": {"suffix": "19_1"}, "tai": {"module": {"name": "piu4", "location": "3"}, "hostif": {"name": "0", "index": 0}}},
      {"interface": {"suffix": "20_1"}, "tai": {"module": {"name": "piu4", "location": "3"}, "hostif": {"name": "1", "index": 1}}},
      {"component": {"name": "piu1"}, "tai": {"module": {"name": "piu1", "location": "0"}, "netif": {"name": "0", "index": 0}}},
      {"component": {"name": "piu2"}, "tai": {"module": {"name": "piu2", "location": "1"}, "netif": {"name": "0", "index": 0}}},
      {"component": {"name": "piu3"}, "tai": {"module": {"name": "piu3", "location": "2"}, "netif": {"name": "0", "index": 0}}},
      {"component": {"name": "piu4"}, "tai": {"module": {"name": "piu4", "location": "3"}, "netif": {"name": "0", "index": 0}}},
      {"component": {"name": "piu5"}, "tai": {"module": {"name": "piu5", "location": "4"}, "netif": {"name": "0", "index": 0}}},
      {"component": {"name": "piu6"}, "tai": {"module": {"name": "piu6", "location": "5"}, "netif": {"name": "0", "index": 0}}}
    ]

---

apiVersion: batch/v1
kind: Job
metadata:
    name: prep-gs-mgmt
spec:
    template:
        spec:
            restartPolicy: Never
            initContainers: # run prep-sysrepo and prep-np sequentially
            - name: prep-sysrepo
              image: ghcr.io/oopt-goldstone/mgmt/north-cli:latest
              imagePullPolicy: IfNotPresent
              command: ["gs-yang.py", "--install", "south-onlp", "south-sonic", "south-tai", "south-system", "xlate-oc"]
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - name: prep-np
              image: ghcr.io/oopt-goldstone/mgmt/north-netconf:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', '$NP2/setup.sh && $NP2/merge_hostkey.sh && $NP2/merge_config.sh']
              env:
              - name: NP2
                value: /usr/local/share/netopeer2/scripts
              - name: NP2_MODULE_OWNER
                value: root
              - name: NP2_MODULE_GROUP
                value: root
              - name: NP2_MODULE_PERMS
                value: "600"
              - name: NP2_MODULE_DIR
                value: /usr/local/share/yang/modules/netopeer2
              volumeMounts:
              - mountPath: /dev/shm
                name: shm
              - mountPath: /var/lib/sysrepo
                name: sysrepo
            containers:
            - name: job-done
              image: ghcr.io/oopt-goldstone/mgmt/north-cli:latest
              imagePullPolicy: IfNotPresent
              command: ["sysrepoctl", "-l"]
              volumeMounts:
              - mountPath: /dev/shm
                name: shm
              - mountPath: /var/lib/sysrepo
                name: sysrepo
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
