apiVersion: v1
kind: ConfigMap
metadata:
  name: snmpd-config
data:
    snmpd.conf: | 
        rwuser  admin noauth 
        rouser  user noauth 
        rwcommunity  admin  
        rocommunity  user  
        master agentx
        agentxsocket tcp:localhost:3161

---
apiVersion: v1
kind: Service
metadata:
  name: gs-mgmt-snmp
spec:
  type: NodePort
  ports:
    - port: 161
      targetPort: 161
      protocol: UDP
      name: snmp
      nodePort: 30010
  selector:
    app: gs-mgmt-snmp

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-snmp
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-snmp
    template:
        metadata:
            labels:
                app: gs-mgmt-snmp
        spec:
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: snmpd
              image: docker.io/microsonic/gs-mgmt-snmpd:latest
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 161
              command: ['snmpd', '-f', '-C', '-c', '/etc/snmp/snmpd.conf']
              volumeMounts:
              - name: snmpd-config
                mountPath: /etc/snmp
            - name: agentx
              image: docker.io/microsonic/gs-mgmt-north-snmp:latest
              imagePullPolicy: IfNotPresent
              command: ['gsnorthd-snmp', '-v']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: sonic-db-config
                mountPath: /var/run/redis/sonic-db/
              - name: redis-sock
                mountPath: /var/run/redis/
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: snmpd-config
              configMap:
                name: snmpd-config
            - name: sonic-db-config
              configMap:
                  name: sonic-db-config
            - name: redis-sock
              hostPath:
                  path: /tmp
                  type: Directory
