apiVersion: v1
kind: ConfigMap
metadata:
  name: usonic-config
data:
  lanemap.ini: |
    vEthernet1:1,2,3,4
    vEthernet2:5,6,7,8
  lanemap.ini.j2: "# name lanes\n{% for i in interfaces -%}\n{{ i['name'] }}:{{ i['lanes'] }}\n{% endfor %}"
  port_config.ini: |
    Ethernet1 1,2,3,4
    Ethernet2 5,6,7,8
  port_config.ini.j2: "# name lanes alias index speed\n
{% for i in interfaces -%}\n
{{ '%-15s' | format(i['name']) }} {{ '%-15s' | format(i['lanes']) }} {{ '%-15s' | format(i['alias']) }} {{ '%-5s' | format(i['index']) }} {{ i['speed'] }}\n
{% endfor %}"
  config.bcm: |
    # dummy
  config.bcm.j2: |
    # dummy
  interfaces.json: |
    [
    {"port": 1, "first_lane": 1, "lane_num": 4, "alias_prefix": "QSFP1", "index": 1, "speed": 100000},
    {"port": 2, "first_lane": 5, "lane_num": 4, "alias_prefix": "QSFP2", "index": 5, "speed": 100000}
    ]
  sai.profile: |
    SAI_VS_SWITCH_TYPE=SAI_VS_SWITCH_TYPE_BCM56850
    SAI_VS_INTERFACE_LANE_MAP_FILE=/etc/sonic/lanemap.ini

---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: south-sonic
    labels:
        gs-mgmt: south-sonic

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: south-sonic
    labels:
        gs-mgmt: south-sonic
roleRef:
  kind: ClusterRole
  name: usonic-manage
  apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: south-sonic
   namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: usonic-manage
    labels:
        gs-mgmt: south-sonic
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","update","patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get","list","watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["*"]

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: south-sonic
    labels:
        app: gs-mgmt
        gs-mgmt: south-sonic
spec:
    selector:
        matchLabels:
            app: south-sonic
    template:
        metadata:
            labels:
                app: south-sonic
        spec:
            serviceAccountName: south-sonic
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: sonic
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt-south-sonic:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-sonic']
              args: ['--verbose', "$(PLATFORM_FILE)"]
              env:
              - name: USONIC_TEMPLATE_DIR
                value: /var/lib/usonic
              - name: PLATFORM_FILE
                value: /var/lib/current/platform.json
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: sonic-db-config
                mountPath: /var/run/redis/sonic-db/
              - name: usonic-config
                mountPath: /var/lib/usonic
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 2
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 120
                periodSeconds: 1
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: sonic-db-config
              configMap:
                  name: sonic-db-config
            - name: usonic-config
              configMap:
                  name: usonic-config
