apiVersion: v1
kind: ConfigMap
metadata:
  name: goldstone-version
data:
  versions.json: |
      {"PRODUCT_ID_VERSION": "latest"}

---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: south-system
    labels:
        gs-mgmt: south-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: south-system
    labels:
        gs-mgmt: south-system
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: south-system
  namespace: default


---
apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: south-system
    labels:
        app: gs-mgmt
        gs-mgmt: south-system
spec:
    selector:
        matchLabels:
            app: south-system
    template:
        metadata:
            labels:
                app: south-system
        spec:
            serviceAccountName: south-system
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: south-system
              image: ghcr.io/oopt-goldstone/mgmt/south-system:latest
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-system', '-v']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: goldstone-version
                mountPath: /etc/goldstone/loader
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: goldstone-version
              configMap:
                  name: goldstone-version
