apiVersion: v1
kind: ConfigMap
metadata:
    name: onl-platform
data:
    platform: "x86-64-kvm-x86-64-r0"

---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: south-onlp
    labels:
        gs-mgmt: south-onlp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: south-onlp
    labels:
        gs-mgmt: south-onlp
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: south-onlp
  namespace: default

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: south-onlp
    labels:
        app: gs-mgmt
        gs-mgmt: south-onlp
spec:
    selector:
        matchLabels:
            app: south-onlp
    template:
        metadata:
            labels:
                app: south-onlp
        spec:
            serviceAccountName: south-onlp
            initContainers:
            - name: wait-prep
              image: docker.io/lachlanevenson/k8s-kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: onlp
              image: ghcr.io/oopt-goldstone/goldstone-mgmt/gs-mgmt-south-onlp:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', 'ln -sf /lib/platform-config/x86-64-kvm-x86-64-r0/onl/lib/libonlp-x86-64-kvm-x86-64.so /lib/x86_64-linux-gnu/libonlp-platform.so.1 && gssouthd-onlp -v']
              env:
              - name: PYTHONPATH
                value: /usr/lib/python3/dist-packages
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: onl-platform
                mountPath: /etc/onl/
              securityContext:
                privileged: true
                capabilities:
                  add:
                  - IPC_OWNER
                  - IPC_LOCK
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 2
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 120
                periodSeconds: 1
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: onl-platform
              configMap:
                name: onl-platform
