apiVersion: v1
kind: ServiceAccount
metadata:
    name: xlate-oc
    labels:
        gs-mgmt: xlate-oc

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: xlate-oc
    labels:
        gs-mgmt: xlate-oc
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: xlate-oc
  namespace: default

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: xlate-oc
    labels:
        app: gs-mgmt
        gs-mgmt: xlate-oc
spec:
    selector:
        matchLabels:
            app: xlate-oc
    template:
        metadata:
            labels:
                app: xlate-oc
        spec:
            serviceAccountName: xlate-oc
            initContainers:
            - name: wait-prep
              image: docker.io/lachlanevenson/k8s-kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: xlate-openconfig
              image: ghcr.io/oopt-goldstone/mgmt/xlate-oc:latest
              imagePullPolicy: IfNotPresent
              command: ['gsxlated-openconfig']
              args: ['--verbose', '$(OPERATIONAL_MODES_FILE)']
              env:
              - name: OPERATIONAL_MODES_FILE
                value: /current/operational-modes.json
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              # NOTE: Enable if you want to overwrite default /current/operational-modes.json.
              # - name: current
              #   mountPath: /current
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 10
                periodSeconds: 5
                timeoutSeconds: 5
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 30
                periodSeconds: 10
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            # NOTE: Enable if you want to overwrite default /current/operational-modes.json.
            # - name: current
            #   hostPath:
            #       path: /var/lib/goldstone/device/current
