apiVersion: v1
kind: ServiceAccount
metadata:
    name: gs-mgmt-sonic-svc
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: gs-mgmt-sonic-svc
    namespace: default
roleRef:
  kind: ClusterRole
  name: usonic-manage
  apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: gs-mgmt-sonic-svc
   namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: usonic-manage
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","update","patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get","list","watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["*"]

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-sonic
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-sonic
    template:
        metadata:
            labels:
                app: gs-mgmt-sonic
        spec:
            serviceAccountName: gs-mgmt-sonic-svc
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: sonic
              image: docker.io/gs-test/gs-mgmt-south-sonic:latest-amd64
              imagePullPolicy: IfNotPresent
              #              command: ['sleep', 'infinity']
              command: ['gssouthd-sonic']
              args: ['--verbose']
              env:
              - name: USONIC_TEMPLATE_DIR
                value: /var/lib/current
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: sonic-db-config
                mountPath: /var/run/redis/sonic-db/
              - name: current
                mountPath: /var/lib/current
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 1
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 30
                periodSeconds: 10
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: current
              hostPath:
                  path: /var/lib/goldstone/device/current/usonic
            - name: sonic-db-config
              configMap:
                  name: sonic-db-config
