apiVersion: v1
kind: ServiceAccount
metadata:
    name: south-sonic
    labels:
        gs-mgmt: south-sonic

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: south-sonic
    labels:
        gs-mgmt: south-sonic
roleRef:
  kind: ClusterRole
  name: usonic-manage
  apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: south-sonic
   namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: usonic-manage
    labels:
        gs-mgmt: south-sonic
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","update","patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get","list","watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["*"]

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: south-sonic
    labels:
        app: gs-mgmt
        gs-mgmt: south-sonic
spec:
    selector:
        matchLabels:
            app: south-sonic
    template:
        metadata:
            labels:
                app: south-sonic
        spec:
            serviceAccountName: south-sonic
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: sonic
              image: docker.io/gs-test/south-sonic:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-sonic']
              args: ['--verbose', "$(PLATFORM_FILE)"]
              env:
              - name: USONIC_TEMPLATE_DIR
                value: /var/lib/current/usonic
              - name: PLATFORM_FILE
                value: /var/lib/current/platform.json
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: sonic-db-config
                mountPath: /var/run/redis/sonic-db/
              - name: current
                mountPath: /var/lib/current
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 2
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 120
                periodSeconds: 1
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: sonic-db-config
              configMap:
                  name: sonic-db-config
            - name: current
              hostPath:
                  path: /var/lib/goldstone/device/current
