apiVersion: v1
kind: ServiceAccount
metadata:
    name: south-tai
    labels:
        gs-mgmt: south-tai

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: south-tai
    labels:
        gs-mgmt: south-tai
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: south-tai
  namespace: default

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: south-tai
    labels:
        app: gs-mgmt
        gs-mgmt: south-tai
spec:
    selector:
        matchLabels:
            app: south-tai
    template:
        metadata:
            labels:
                app: south-tai
        spec:
            serviceAccountName: south-tai
            initContainers:
            - name: wait-prep
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            - name: wait-onlp
              image: docker.io/bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', "kubectl wait --for=condition=ready pods/$(kubectl get pods -l app=south-onlp -o jsonpath='{.items[0].metadata.name}')"]
            containers:
            - name: tai
              image: docker.io/gs-test/gs-mgmt-south-tai:latest-amd64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-tai']
              args: ['--taish-server', "$(TAISH_SERVER_SERVICE_HOST):$(TAISH_SERVER_SERVICE_PORT)", "--verbose"]
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 2
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 120
                periodSeconds: 1
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
