swig:
	$(MAKE) -C sysrepo-py/python/
	cp sysrepo-py/python/sysrepo.py /usr/lib/python3/dist-packages/
	cp sysrepo-py/python/_sysrepo.so /usr/lib/python3/dist-packages/

clean:
	$(MAKE) -C sysrepo-py/python clean
