on:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
        default: ghcr.io/oopt-goldstone/mgmt
      file:
        required: true
        type: string
      target:
        required: true
        type: string
      build-args:
        required: false
        type: string
    outputs:
      tags:
        value: ${{ jobs.push.output.tags }}
      labels:
        value: ${{ jobs.push.output.labels }}

jobs:
  push:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      -
        name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta for builder
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "${{ inputs.repo }}/${{ inputs.target }}"
      -
        name: Build agent
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: ${{ inputs.file }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ inputs.target }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ inputs.build-args }}
