name: push

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'releases/v*'
    tags:
      - 'v*'

jobs:
  builder:
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      file: ./docker/builder.Dockerfile
      targets: >-
        ["builder"]
  build-host-packages:
    needs: builder
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      file: ./docker/builder.Dockerfile
      targets: >-
        ["host-packages"]
  build-snmpd:
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    with:
      file: ./docker/snmpd.Dockerfile
      targets: >-
        ["snmpd"]
  build-agents:
    needs: builder
    uses: ./.github/workflows/build_image.yaml
    secrets: inherit
    # using matrix here is not supported yet
    # https://github.community/t/reusable-workflow-with-strategy-matrix/205676/8
    with:
      file: ./docker/agent.Dockerfile
      build-args: GS_MGMT_BUILDER_IMAGE=${{ needs.builder.outputs.tags }}
      targets: >-
        ["north-cli", "north-snmp", "north-netconf", "north-notif", "north-gnmi", "south-sonic", "south-ocnos", "south-tai", "south-onlp", "south-system", "south-gearbox", "south-dpll", "south-netlink", "xlate-oc", "xlate-or", "system-telemetry"]
