apiVersion: v1
kind: Service
metadata:
    name: netopeer2
spec:
  type: LoadBalancer
  selector:
      app: gs-mgmt-np2
  ports:
  - protocol: TCP
    port: 830
    targetPort: 830
    name: netconf

---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: gs-mgmt
    namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: gs-mgmt
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: gs-mgmt
  namespace: default

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-np2
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-np2
    template:
        metadata:
            labels:
                app: gs-mgmt-np2
        spec:
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/library/kubectl:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: netopeer2
              image: docker.io/gs-test/gs-mgmt-netopeer2:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['netopeer2-server']
              args: ['-d', '-v', '2']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: home
                mountPath: /home
                readOnly: true
              - name: passwd
                mountPath: /etc/passwd
                readOnly: true
              - name: shadow
                mountPath: /etc/shadow
                readOnly: true
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: home
              hostPath:
                  path: /home
            - name: passwd
              hostPath:
                  path: /etc/passwd
            - name: shadow
              hostPath:
                  path: /etc/shadow


---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-tai
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-tai
    template:
        metadata:
            labels:
                app: gs-mgmt-tai
        spec:
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/library/kubectl:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            - name: wait-onlp
              image: docker.io/library/kubectl:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', "kubectl wait --for=condition=ready pods/$(kubectl get pods -l app=gs-mgmt-onlp -o jsonpath='{.items[0].metadata.name}')"]
            containers:
            - name: tai
              image: docker.io/gs-test/gs-mgmt-south-tai:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-tai']
              args: ['--taish-server', "$(TAISH_SERVER_SERVICE_HOST):$(TAISH_SERVER_SERVICE_PORT)", "--verbose"]
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 1
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 30
                periodSeconds: 10
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-onlp
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-onlp
    template:
        metadata:
            labels:
                app: gs-mgmt-onlp
        spec:
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/library/kubectl:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: onlp
              image: docker.io/gs-test/gs-mgmt-south-onlp:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-onlp']
              args: ['--verbose']
              env:
              - name: PYTHONPATH
                value: /usr/lib/python3/dist-packages
              volumeMounts:
              - name: dev
                mountPath: /dev
              - name: shm
                mountPath: /dev/shm
              - name: sys
                mountPath: /sys
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: onl
                mountPath: /etc/onl/
              - name: host-lib
                mountPath: /lib/aarch64-linux-gnu/libonlp-platform.so.1
              - name: host-i2c-lib
                mountPath: /lib/aarch64-linux-gnu/libi2c.so.0
              securityContext:
                privileged: true
                capabilities:
                  add:
                  - IPC_OWNER
                  - IPC_LOCK
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 1
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 30
                periodSeconds: 10
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: dev
              hostPath:
                  path: /dev
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sys
              hostPath:
                  path: /sys
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: onl
              hostPath:
                path: /etc/onl
            - name: host-lib
              hostPath:
                path: /lib/aarch64-linux-gnu/libonlp-platform.so
            - name: host-i2c-lib
              hostPath:
                path: /usr/lib/aarch64-linux-gnu/libi2c.so.0.1.1

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: gs-mgmt-notif
    labels:
        app: gs-mgmt
spec:
    selector:
        matchLabels:
            app: gs-mgmt-notif
    template:
        metadata:
            labels:
                app: gs-mgmt-notif
        spec:
            serviceAccountName: gs-mgmt
            initContainers:
            - name: wait-prep
              image: docker.io/library/kubectl:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: notif
              image: docker.io/gs-test/gs-mgmt-south-notif:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-notif']
              args: ['--verbose']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 1
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 30
                periodSeconds: 10
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
