apiVersion: v1
kind: Service
metadata:
    name: north-netconf
spec:
  type: LoadBalancer
  selector:
      app: north-netconf
  ports:
  - protocol: TCP
    port: 830
    targetPort: 830
    name: netconf

---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: north-netconf
    labels:
        gs-mgmt: north-netconf

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: north-netconf
    labels:
        gs-mgmt: north-netconf
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: north-netconf
  namespace: default

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: north-netconf
    labels:
        app: gs-mgmt
        gs-mgmt: north-netconf
spec:
    selector:
        matchLabels:
            app: north-netconf
    template:
        metadata:
            labels:
                app: north-netconf
        spec:
            serviceAccountName: north-netconf
            initContainers:
            - name: wait-prep
              image: docker.io/lachlanevenson/k8s-kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: notif
              image: docker.io/gs-test/north-netconf:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['netopeer2-server']
              args: ['-d', '-v', '2', '-t', '60']
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: home
                mountPath: /home
                readOnly: true
              - name: passwd
                mountPath: /etc/passwd
                readOnly: true
              - name: shadow
                mountPath: /etc/shadow
                readOnly: true
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: home
              hostPath:
                  path: /home
            - name: passwd
              hostPath:
                  path: /etc/passwd
            - name: shadow
              hostPath:
                  path: /etc/shadow
