apiVersion: batch/v1
kind: Job
metadata:
    name: prep-gs-mgmt
spec:
    template:
        spec:
            restartPolicy: Never
            initContainers: # run prep-sysrepo and prep-np sequentially
            - name: prep-sysrepo
              image: docker.io/gs-test/south-onlp:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ["gs-yang.py", "--install", "south-onlp", "south-gearbox", "south-dpll", "south-tai", "south-system", "xlate-oc"]
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
            - name: prep-np
              image: docker.io/gs-test/north-netconf:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['sh', '-c', '$NP2/setup.sh && $NP2/merge_hostkey.sh && $NP2/merge_config.sh']
              env:
              - name: NP2
                value: /usr/local/share/netopeer2/scripts
              - name: NP2_MODULE_OWNER
                value: root
              - name: NP2_MODULE_GROUP
                value: root
              - name: NP2_MODULE_PERMS
                value: "600"
              - name: NP2_MODULE_DIR
                value: /usr/local/share/yang/modules/netopeer2
              volumeMounts:
              - mountPath: /dev/shm
                name: shm
              - mountPath: /var/lib/sysrepo
                name: sysrepo
            containers:
            - name: job-done
              image: docker.io/gs-test/south-onlp:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ["sysrepoctl", "-l"]
              volumeMounts:
              - mountPath: /dev/shm
                name: shm
              - mountPath: /var/lib/sysrepo
                name: sysrepo
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
