apiVersion: v1
kind: ServiceAccount
metadata:
    name: south-onlp
    labels:
        gs-mgmt: south-onlp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: south-onlp
    labels:
        gs-mgmt: south-onlp
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: south-onlp
  namespace: default

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: south-onlp
    labels:
        app: gs-mgmt
        gs-mgmt: south-onlp
spec:
    selector:
        matchLabels:
            app: south-onlp
    template:
        metadata:
            labels:
                app: south-onlp
        spec:
            serviceAccountName: south-onlp
            initContainers:
            - name: wait-prep
              image: docker.io/lachlanevenson/k8s-kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: onlp
              image: docker.io/gs-test/gs-mgmt-south-onlp:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-onlp']
              args: ['--verbose']
              env:
              - name: PYTHONPATH
                value: /usr/lib/python3/dist-packages
              volumeMounts:
              - name: dev
                mountPath: /dev
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: onl
                mountPath: /etc/onl/
              - name: sys
                mountPath: /sys
              - name: host-lib
                mountPath: /lib/aarch64-linux-gnu/libonlp-platform.so.1
              securityContext:
                privileged: true
                capabilities:
                  add:
                  - IPC_OWNER
                  - IPC_LOCK
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 2
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 120
                periodSeconds: 1
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: dev
              hostPath:
                  path: /dev
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: onl
              hostPath:
                path: /etc/onl
            - name: sys
              hostPath:
                path: /sys
            - name: host-lib
              hostPath:
                path: /lib/aarch64-linux-gnu/libonlp-platform.so
