apiVersion: v1
kind: ServiceAccount
metadata:
    name: south-dpll
    labels:
        gs-mgmt: south-dpll

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: south-dpll
    labels:
        gs-mgmt: south-dpll
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
subjects:
- kind: ServiceAccount
  name: south-dpll
  namespace: default

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: south-dpll
    labels:
        app: gs-mgmt
        gs-mgmt: south-dpll
spec:
    selector:
        matchLabels:
            app: south-dpll
    template:
        metadata:
            labels:
                app: south-dpll
        spec:
            serviceAccountName: south-dpll
            initContainers:
            - name: wait-prep
              image: docker.io/lachlanevenson/k8s-kubectl:latest
              imagePullPolicy: IfNotPresent
              command: ['kubectl', 'wait', '--for=condition=complete', 'job/prep-gs-mgmt']
            containers:
            - name: dpll
              image: docker.io/gs-test/gs-mgmt-south-dpll:latest-arm64
              imagePullPolicy: IfNotPresent
              command: ['gssouthd-dpll']
              args: ['--taish-server', "$(TAI_DPLL_SERVICE_HOST):$(TAI_DPLL_SERVICE_PORT)", "--verbose", "$(PLATFORM_FILE)"]
              env:
              - name: PLATFORM_FILE
                value: /current/platform.json
              volumeMounts:
              - name: shm
                mountPath: /dev/shm
              - name: sysrepo
                mountPath: /var/lib/sysrepo
              - name: current
                mountPath: /current
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 2
                periodSeconds: 10
              startupProbe:
                httpGet:
                  path: /healthz
                  port: liveness-port
                failureThreshold: 30
                periodSeconds: 10
              ports:
              - name: liveness-port
                containerPort: 8080
            volumes:
            - name: shm
              hostPath:
                  path: /dev/shm
            - name: sysrepo
              hostPath:
                  path: /var/lib/sysrepo
            - name: current
              hostPath:
                  path: /var/lib/goldstone/device/current
